server:
  port: 9090
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/library-management?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
freemarker:
  checkTemplateLocation: false

mybatis:
  mapper-locations: classpath:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true #下划线
